 const CountryName = [
{country:"United States of America"},
{country:"Mexico"},
{country:"Nigeria"},
{country:"Lebanon"},
{country:"Russia"},
{country:"Saudi Arabia"},
{country:"Angola"},
{country:"Egypt"},
{country:"South Africa"},
{country:"Ukraine"},
{country:"India"},
{country:"Azerbaijan"},
{country:"China"},
{country:"Colombia"},
{country:"Niger"},
{country:"Libya"},
{country:"Brazil"},
{country:"Indonesia"},
{country:"Mali"},
{country:"Iraq"},
{country:"Iran"},
{country:"South Sudan"},
{country:"Venezuela"},
{country:"Burkina Faso"},	
{country:"Germany"},
{country:"United Kingdom"},
{country:"Kuwait"},
{country:"Egypt"},
{country:"Canada"},
{country:"Mexico"},
{country:"Argentina"},
{country:"Japan"},
{country:"Spain"},
{country:"Austria"},
{country:"Estonia"},
{country:"Nigeria"},
{country:"Hungary"},
{country:"Australia"},
{country:"Morocco"},
{country:"South Africa"},
{country:"Greece"},
{country:"Qatar"},
{country:"Oman"},
{country:"Angola"},
{country:"Malaysia"},
{country:"Ukraine"},
{country:"Jordan"},
{country:"Syria"},
{country:"Ethiopia"},
{country:"Venezuela"},
{country:"Norway"},
{country:"Brazil"},
{country:"Ghana"},
{country:"Pakistan"},
{country:"Kazakhstan"},
{country:"Japan"},
{country:"Gabon"},
{country:"United Arab Emirates"},
{country:"Germany"},
{country:"Algeria"},
{country:"Turkey"},
{country:"Ghana"},
{country:"Belize"},
{country:"Cyprus"},
]
export default CountryName;